-- MySQL Script generated by MySQL Workbench
-- Sun Jul 31 01:33:15 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_project` (
  `id_project` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  `budget` INT NOT NULL,
  `document` VARCHAR(50) NULL,
  `deadline` DATETIME NULL,
  `t_assoc_sw_id_assoc_sw` INT NOT NULL,
  PRIMARY KEY (`id_project`, `t_assoc_sw_id_assoc_sw`),
  UNIQUE INDEX `idt_project_UNIQUE` (`id_project` ASC),
  INDEX `fk_t_project_t_assoc_sw1_idx` (`t_assoc_sw_id_assoc_sw` ASC),
  CONSTRAINT `fk_t_project_t_assoc_sw1`
    FOREIGN KEY (`t_assoc_sw_id_assoc_sw`)
    REFERENCES `mydb`.`t_assoc_sw` (`id_assoc_sw`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_assoc-sui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_assoc-sui` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_assoc_tun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_assoc_tun` (
  `idt_assoc_tun` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  `logo` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`idt_assoc_tun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_student` (
  `idt_student` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  `cv` VARCHAR(45) NULL,
  `t_studentcol` VARCHAR(45) NULL,
  `t_assoc_tun_idt_assoc_tun` INT NOT NULL,
  PRIMARY KEY (`idt_student`, `t_assoc_tun_idt_assoc_tun`),
  INDEX `fk_t_student_t_assoc_tun1_idx` (`t_assoc_tun_idt_assoc_tun` ASC),
  CONSTRAINT `fk_t_student_t_assoc_tun1`
    FOREIGN KEY (`t_assoc_tun_idt_assoc_tun`)
    REFERENCES `mydb`.`t_assoc_tun` (`idt_assoc_tun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_assoc_sw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_assoc_sw` (
  `id_assoc_sw` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `logo` VARCHAR(50) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`id_assoc_sw`),
  UNIQUE INDEX `id_assoc_sw_UNIQUE` (`id_assoc_sw` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_project` (
  `id_project` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL,
  `budget` INT NOT NULL,
  `document` VARCHAR(50) NULL,
  `deadline` DATETIME NULL,
  `t_assoc_sw_id_assoc_sw` INT NOT NULL,
  PRIMARY KEY (`id_project`, `t_assoc_sw_id_assoc_sw`),
  UNIQUE INDEX `idt_project_UNIQUE` (`id_project` ASC),
  INDEX `fk_t_project_t_assoc_sw1_idx` (`t_assoc_sw_id_assoc_sw` ASC),
  CONSTRAINT `fk_t_project_t_assoc_sw1`
    FOREIGN KEY (`t_assoc_sw_id_assoc_sw`)
    REFERENCES `mydb`.`t_assoc_sw` (`id_assoc_sw`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_submission` (
  `idt_submission` INT NOT NULL AUTO_INCREMENT,
  `bid` DOUBLE NOT NULL,
  `t_project_id_project` INT NOT NULL,
  PRIMARY KEY (`idt_submission`, `t_project_id_project`),
  INDEX `fk_t_submission_t_project1_idx` (`t_project_id_project` ASC),
  CONSTRAINT `fk_t_submission_t_project1`
    FOREIGN KEY (`t_project_id_project`)
    REFERENCES `mydb`.`t_project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_team` (
  `id_team` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `t_teamcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_team`),
  UNIQUE INDEX `idt_team_UNIQUE` (`id_team` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_accepted_submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_accepted_submission` (
  `id_accepted_submission` INT NULL AUTO_INCREMENT,
  `rating` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_accepted_submission`),
  UNIQUE INDEX `idt_accepted_submission_UNIQUE` (`id_accepted_submission` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_student_has_t_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_student_has_t_team` (
  `t_student_idt_student` INT NOT NULL,
  `t_team_id_team` INT NOT NULL,
  PRIMARY KEY (`t_student_idt_student`, `t_team_id_team`),
  INDEX `fk_t_student_has_t_team_t_team1_idx` (`t_team_id_team` ASC),
  INDEX `fk_t_student_has_t_team_t_student_idx` (`t_student_idt_student` ASC),
  CONSTRAINT `fk_t_student_has_t_team_t_student`
    FOREIGN KEY (`t_student_idt_student`)
    REFERENCES `mydb`.`t_student` (`idt_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_student_has_t_team_t_team1`
    FOREIGN KEY (`t_team_id_team`)
    REFERENCES `mydb`.`t_team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_team_has_t_submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_team_has_t_submission` (
  `t_team_id_team` INT NOT NULL,
  `t_submission_idt_submission` INT NOT NULL,
  PRIMARY KEY (`t_team_id_team`, `t_submission_idt_submission`),
  INDEX `fk_t_team_has_t_submission_t_submission1_idx` (`t_submission_idt_submission` ASC),
  INDEX `fk_t_team_has_t_submission_t_team1_idx` (`t_team_id_team` ASC),
  CONSTRAINT `fk_t_team_has_t_submission_t_team1`
    FOREIGN KEY (`t_team_id_team`)
    REFERENCES `mydb`.`t_team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_team_has_t_submission_t_submission1`
    FOREIGN KEY (`t_submission_idt_submission`)
    REFERENCES `mydb`.`t_submission` (`idt_submission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_student_has_t_submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_student_has_t_submission` (
  `t_student_idt_student` INT NOT NULL,
  `t_submission_idt_submission` INT NOT NULL,
  PRIMARY KEY (`t_student_idt_student`, `t_submission_idt_submission`),
  INDEX `fk_t_student_has_t_submission_t_submission1_idx` (`t_submission_idt_submission` ASC),
  INDEX `fk_t_student_has_t_submission_t_student1_idx` (`t_student_idt_student` ASC),
  CONSTRAINT `fk_t_student_has_t_submission_t_student1`
    FOREIGN KEY (`t_student_idt_student`)
    REFERENCES `mydb`.`t_student` (`idt_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_student_has_t_submission_t_submission1`
    FOREIGN KEY (`t_submission_idt_submission`)
    REFERENCES `mydb`.`t_submission` (`idt_submission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
